In [1]:
import tweepy
import csv
import json
import pandas as pd
import requests
import re
import time

First part of the program where the data will be extracted and will be saved in json file

In [2]:
#loading twitter API credentials from the file which was saved
with open('twitter_credentials.json') as cred_data:
    info = json.load(cred_data)
    consumer_key = info['CONSUMER_KEY']
    consumer_secret = info['CONSUMER_SECRET']
    access_key = info['ACCESS_KEY']
    access_secret = info['ACCESS_SECRET']

In [3]:
# initialization of a list to hold all Tweets
alltweets = []

In [4]:
# Authorization and initialization
auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_key, access_secret)
api = tweepy.API(auth)

In [5]:
# We will get the tweets with multiple requests of 200 tweets each
new_tweets = api.user_timeline(screen_name="midasIIITD", count=200)
# Appending the json part of the data to list
for tweet in new_tweets:
    alltweets.append(tweet._json)

In [13]:
# save id of 1 less than the oldest tweet
oldest = alltweets[-1]["id"] - 1

In [14]:
# grabbing tweets till none are left
while len(new_tweets) > 0:  
    # all subsiquent requests use the max_id param to prevent duplicates
    new_tweets = api.user_timeline(screen_name = "midasIIITD",count=200, max_id=oldest)

    # save most recent tweets
    # Appending the json part of the data to list
    for tweet in new_tweets:
        alltweets.append(tweet._json)
    oldest = alltweets[-1]["id"] - 1

    print("...%s tweets downloaded so far" % (len(alltweets)))

print("Total tweets downloaded %s" % (len(alltweets)))

...331 tweets downloaded so far
...331 tweets downloaded so far
Total tweets downloaded 331

In [36]:
len_media = []

In [37]:
for i in range(len(alltweets)):
    try:
        len_media.append(len(alltweets[i]['entities']['media']))
    except:
        len_media.append(0)

In [92]:
# Creating a new JSON file and dumping the value into it
file = open('tweet.json', 'w')
json.dump(alltweets, file,indent = 4)

Second part of the program to parse the json file and display the output in tabular form

In [40]:
col_names = ["text", "Date and time", "number of favorites/likes", "number of retweets","Number of images"]

In [41]:
# function to get no. of retweets
def get_retweet(data):
    try:
        ans = data["retweeted_status"]["retweet_count"] 
    except KeyError:
        ans = data["retweet_count"] 
    return ans

In [42]:
# function to get no. of likes
def get_favorite(data):
    try:
        ans = data["retweeted_status"]["favorite_count"] 
    except KeyError:
        ans = data["favorite_count"] 
    return ans

In [47]:
# dataframe to show in tabular format
df = pd.DataFrame(columns=col_names)

In [51]:
alltweets[4]

{'contributors': None,
 'coordinates': None,
 'created_at': 'Fri Apr 05 16:08:37 +0000 2019',
 'entities': {'hashtags': [],
  'symbols': [],
  'urls': [{'display_url': 'twitter.com/i/web/status/1…',
    'expanded_url': 'https://twitter.com/i/web/status/1114198161562775553',
    'indices': [117, 140],
    'url': 'https://t.co/gZwyr7D2Sw'}],
  'user_mentions': [{'id': 1021355762575073281,
    'id_str': '1021355762575073281',
    'indices': [71, 82],
    'name': 'MIDAS IIITD',
    'screen_name': 'midasIIITD'}]},
 'favorite_count': 10,
 'favorited': False,
 'geo': None,
 'id': 1114198161562775553,
 'id_str': '1114198161562775553',
 'in_reply_to_screen_name': None,
 'in_reply_to_status_id': None,
 'in_reply_to_status_id_str': None,
 'in_reply_to_user_id': None,
 'in_reply_to_user_id_str': None,
 'is_quote_status': False,
 'lang': 'en',
 'place': None,
 'retweet_count': 1,
 'retweeted': False,
 'source': '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
 'text': 'We have emailed the task details to all candidates who have applied to @midasIIITD internship through IIITD portal.… https://t.co/gZwyr7D2Sw',
 'truncated': True,
 'user': {'contributors_enabled': False,
  'created_at': 'Mon Jul 23 11:26:04 +0000 2018',
  'default_profile': True,
  'default_profile_image': False,
  'description': 'MIDAS is a group of researchers at IIIT-Delhi who study, analyze, and build different multimedia systems for society leveraging multimodal information.',
  'entities': {'description': {'urls': []},
   'url': {'urls': [{'display_url': 'midas.iiitd.edu.in',
      'expanded_url': 'http://midas.iiitd.edu.in/',
      'indices': [0, 23],
      'url': 'https://t.co/Uwg7oSM6mE'}]}},
  'favourites_count': 142,
  'follow_request_sent': False,
  'followers_count': 255,
  'following': True,
  'friends_count': 42,
  'geo_enabled': False,
  'has_extended_profile': False,
  'id': 1021355762575073281,
  'id_str': '1021355762575073281',
  'is_translation_enabled': False,
  'is_translator': False,
  'lang': 'en',
  'listed_count': 0,
  'location': 'New Delhi, India',
  'name': 'MIDAS IIITD',
  'notifications': False,
  'profile_background_color': 'F5F8FA',
  'profile_background_image_url': None,
  'profile_background_image_url_https': None,
  'profile_background_tile': False,
  'profile_banner_url': 'https://pbs.twimg.com/profile_banners/1021355762575073281/1554320878',
  'profile_image_url': 'http://pbs.twimg.com/profile_images/1021356444921212928/WmSTJCUs_normal.jpg',
  'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1021356444921212928/WmSTJCUs_normal.jpg',
  'profile_link_color': '1DA1F2',
  'profile_sidebar_border_color': 'C0DEED',
  'profile_sidebar_fill_color': 'DDEEF6',
  'profile_text_color': '333333',
  'profile_use_background_image': True,
  'protected': False,
  'screen_name': 'midasIIITD',
  'statuses_count': 331,
  'time_zone': None,
  'translator_type': 'none',
  'url': 'https://t.co/Uwg7oSM6mE',
  'utc_offset': None,
  'verified': False}}

In [49]:
for i,tw in enumerate(all_tweets):
    text = re.sub(r"http\S+", "", tw["text"])
    dt = tw["created_at"].split()
    date = dt[2]+'-'+dt[1]+'-'+dt[-1]+"|"+dt[3]
    favorite = get_favorite(tw)
    retweet = get_retweet(tw)
#     images = get_photos(tw)
    df.loc[len(df)] = [text, date, favorite, retweet,len_media[i]]

In [50]:
df

,text,Date and time,number of favorites/likes,number of retweets,Number of images
0,RT @kdnuggets: Top 8 #Free Must-Read #Books on...,06-Apr-2019|17:11:29,15,2,0
1,@nupur_baghel @PennDATS Congratulation @nupur_...,06-Apr-2019|16:43:27,14,3,0
2,We have emailed the task details to all candid...,05-Apr-2019|16:08:37,10,1,0
3,RT @rfpvjr: Our NAACL paper on polarization in...,05-Apr-2019|04:05:11,49,16,0
4,RT @kdnuggets: Effective Transfer Learning For...,05-Apr-2019|04:04:43,20,10,0
5,RT @stanfordnlp: What’s new in @Stanford CS224...,03-Apr-2019|18:31:53,223,58,0
6,RT @DeepMindAI: Today we're releasing a large-...,03-Apr-2019|17:04:32,2356,849,1
7,RT @ylecun: Congratulations Jitendra Malik !\n...,03-Apr-2019|09:03:40,150,16,0
8,RT @IIITDelhi: Another chance to take admissio...,03-Apr-2019|07:46:02,4,4,0
9,Dear @midasIIITD internship candidates who hav...,02-Apr-2019|04:20:13,8,1,0
10,Looking forward to your paper submission to @I...,02-Apr-2019|02:44:54,5,1,0
11,RT @ngrams: Reproducibility in multimedia rese...,02-Apr-2019|02:35:44,9,7,0
12,Online application for Admission 2019 at @III...,01-Apr-2019|06:53:08,7,2,0
13,RT @ACMMM19: A final reminder of the Reproduci...,31-Mar-2019|10:21:24,12,10,0
14,RT @isarth23: Thanks for the support and help ...,29-Mar-2019|19:43:24,7,2,0
15,"Since SemEval-2019 will be held June 6-7, 2019...",29-Mar-2019|17:16:40,9,1,0
16,+@aggarwal_kartik.\nCongrats! Wish you many mo...,29-Mar-2019|17:04:30,2,0,0
17,RT @aggarwal_kartik: Our work (@midasIIITD ) a...,29-Mar-2019|17:03:29,6,1,0
18,"Congratulations! @midasIIITD team, @isarth23 @...",29-Mar-2019|17:02:24,9,1,0
19,@EEMLcommunity @radamihalcea too many deadline...,29-Mar-2019|05:35:22,0,0,0
20,RT @stanfordnlp: CS224N Natural Language Proce...,28-Mar-2019|16:55:01,1964,714,0
21,RT @ylecun: Learn PyTorch by running on Google...,28-Mar-2019|16:54:37,644,157,0
22,Dr. Vineeth N Balasubramanian will present a T...,27-Mar-2019|16:09:09,4,1,0
23,RT @ylecun: I am extremely honored to be the r...,27-Mar-2019|11:53:40,7534,1545,0
24,Thanks to all shortlisted candidates for submi...,26-Mar-2019|18:12:27,5,1,0
25,@IEEEBigMM19 @ACMMM19 and 6 days left for work...,26-Mar-2019|05:54:49,2,0,0
26,RT @IEEEBigMM19: Hurry Up!\n6 Days left for Ab...,26-Mar-2019|05:50:10,3,3,0
27,Congratulations @midasIIITD students Simra Sha...,25-Mar-2019|13:01:57,18,1,0
28,The last date for submitting a solution for th...,24-Mar-2019|18:44:01,8,3,0
29,RT @IIITDelhi: @IIITDelhi invites application ...,24-Mar-2019|18:26:02,4,4,0
...,...,...,...,...,...
299,RT @TensorFlow: TensorFlow 1.10.0 has been rel...,09-Aug-2018|05:59:57,567,265,0
300,@midasIIITD is looking for motivated IIITD MTe...,08-Aug-2018|11:30:56,2,1,1
301,@IIITDelhi @ponguru @RatnRajiv The results of ...,08-Aug-2018|05:53:48,3,1,0
302,RT @IIITDelhi: @midasIIITD has secured rank 1 ...,08-Aug-2018|05:45:58,6,1,0
303,RT @kdnuggets: Comparison of Top 6 Python NLP ...,07-Aug-2018|07:16:33,88,40,1
304,Check more details of the 20th IEEE Internatio...,07-Aug-2018|02:05:12,1,1,0
305,MR2AMC@ISM 2018 will be organized by @RatnRaji...,07-Aug-2018|01:58:49,1,1,1
306,"Our workshop proposal named, ""MR2AMC: Multimod...",07-Aug-2018|01:50:33,1,1,0
307,@NUSComputing Congratulations Abdelhak and Pro...,06-Aug-2018|17:48:23,0,0,0
308,RT @goodfellow_ian: One of the most anticipate...,06-Aug-2018|17:46:59,423,103,0
309,@the_dhumketu Great to have you in @midasIIITD,06-Aug-2018|06:06:47,0,0,0
310,Congratulation @soujanyaporia for being appoin...,03-Aug-2018|05:56:33,6,1,1
311,@IIITDelhi @the_dhumketu Thanks team @midasIIITD,01-Aug-2018|11:47:15,5,1,0
312,RT @IIITDelhi: Congratulations @midasIIITD int...,01-Aug-2018|11:20:07,7,4,0
313,RT @learning_pt: Profile of the 5 Indian under...,01-Aug-2018|05:06:47,4,4,1
314,Have a look at the list of accepted papers in ...,31-Jul-2018|12:11:52,1,0,0
315,RT @goodfellow_ian: TensorFuzz automates the ...,31-Jul-2018|02:06:26,756,264,0
316,RT @IIITDelhi: Congratulations Dr. @RatnRajiv ...,30-Jul-2018|07:30:51,14,2,0
317,"RT @ylecun: Jitendra Malik, who directs FAIR-M...",28-Jul-2018|11:07:11,218,57,0
318,RT @kdnuggets: .@Bloomberg launches free cours...,28-Jul-2018|06:14:09,225,105,0
319,RT @TechAtBloomberg: Missed #PyLondinium18? Wa...,28-Jul-2018|06:13:48,7,7,0
320,RT @IIITDelhi: We are delighted to announce th...,28-Jul-2018|04:08:21,36,6,0
321,Get ready for the annual technical fest of @II...,27-Jul-2018|06:46:44,3,2,0
322,Congratulations Dr. @RatnRajiv and team @midas...,27-Jul-2018|04:07:31,8,2,0
323,Congratulations MIDAS @midasIIITD intern Prakh...,25-Jul-2018|05:14:35,5,1,0
324,MIDAS@IIITD foundation.,24-Jul-2018|10:33:23,2,1,0
325,It feels great to be the part of @IIITDelhi.,24-Jul-2018|10:12:34,2,1,0
326,"Thank you, @toonzratn for designing the logo o...",24-Jul-2018|09:46:26,4,1,0
327,We are on Facebook too. Like our page to get o...,23-Jul-2018|16:25:05,3,1,0
328,MIDAS is a group of researchers at IIIT-Delhi ...,23-Jul-2018|12:53:15,7,4,1